/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('@arco-design/web-vue')['Button']
    ASpace: typeof import('@arco-design/web-vue')['Space']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconBxBowlRice: typeof import('~icons/bx/bowl-rice')['default']
    IconHomeAntDesignBankTwotone: typeof import('~icons/home/ant-design-bank-twotone')['default']
    IconUserUilBitcoin: typeof import('~icons/user/uil-bitcoin')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
